# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 694)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 991, 631))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.listWidget = QtWidgets.QListWidget(self.tab_3)
        self.listWidget.setGeometry(QtCore.QRect(190, 40, 781, 521))
        self.listWidget.setObjectName("listWidget")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit.setGeometry(QtCore.QRect(190, 570, 661, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(864, 570, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(710, 10, 51, 20))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(760, 10, 211, 20))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setObjectName("label_7")
        self.ID_LINEEDIT = QtWidgets.QLineEdit(self.tab_3)
        self.ID_LINEEDIT.setGeometry(QtCore.QRect(210, 10, 113, 20))
        self.ID_LINEEDIT.setObjectName("ID_LINEEDIT")
        self.ID_LABEL = QtWidgets.QLabel(self.tab_3)
        self.ID_LABEL.setGeometry(QtCore.QRect(190, 10, 21, 16))
        self.ID_LABEL.setObjectName("ID_LABEL")
        self.CHANNEL_LIST_TREEWIDGET = QtWidgets.QTreeWidget(self.tab_3)
        self.CHANNEL_LIST_TREEWIDGET.setGeometry(QtCore.QRect(10, 40, 171, 471))
        self.CHANNEL_LIST_TREEWIDGET.setObjectName("CHANNEL_LIST_TREEWIDGET")
        item_0 = QtWidgets.QTreeWidgetItem(self.CHANNEL_LIST_TREEWIDGET)
        self.ADD_CHNNEL_BTN = QtWidgets.QPushButton(self.tab_3)
        self.ADD_CHNNEL_BTN.setGeometry(QtCore.QRect(10, 570, 171, 23))
        self.ADD_CHNNEL_BTN.setObjectName("ADD_CHNNEL_BTN")
        self.UPDATE_ID_BTN = QtWidgets.QPushButton(self.tab_3)
        self.UPDATE_ID_BTN.setGeometry(QtCore.QRect(330, 10, 75, 23))
        self.UPDATE_ID_BTN.setObjectName("UPDATE_ID_BTN")
        self.ADD_CHANNEL_NAME_EDIT = QtWidgets.QLineEdit(self.tab_3)
        self.ADD_CHANNEL_NAME_EDIT.setGeometry(QtCore.QRect(10, 540, 171, 20))
        self.ADD_CHANNEL_NAME_EDIT.setObjectName("ADD_CHANNEL_NAME_EDIT")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(10, 520, 171, 16))
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 30, 211, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(360, 30, 41, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 70, 211, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(30, 30, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(310, 30, 41, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 41, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(310, 70, 41, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(360, 70, 41, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 110, 141, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(30, 150, 311, 20))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab_4, "")
        self.STATUS_LABEL = QtWidgets.QLabel(self.centralwidget)
        self.STATUS_LABEL.setGeometry(QtCore.QRect(10, 640, 991, 20))
        self.STATUS_LABEL.setText("")
        self.STATUS_LABEL.setObjectName("STATUS_LABEL")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1010, 23))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGitHub = QtWidgets.QAction(MainWindow)
        self.actionGitHub.setObjectName("actionGitHub")
        self.actionTrello = QtWidgets.QAction(MainWindow)
        self.actionTrello.setObjectName("actionTrello")
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionGitHub)
        self.menuMenu.addAction(self.actionTrello)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Send"))
        self.label_6.setText(_translate("MainWindow", "online:"))
        self.label_7.setText(_translate("MainWindow", "0"))
        self.ID_LABEL.setText(_translate("MainWindow", "ID:"))
        self.CHANNEL_LIST_TREEWIDGET.headerItem().setText(0, _translate("MainWindow", "Channel List"))
        __sortingEnabled = self.CHANNEL_LIST_TREEWIDGET.isSortingEnabled()
        self.CHANNEL_LIST_TREEWIDGET.setSortingEnabled(False)
        self.CHANNEL_LIST_TREEWIDGET.topLevelItem(0).setText(0, _translate("MainWindow", "Default Channel"))
        self.CHANNEL_LIST_TREEWIDGET.setSortingEnabled(__sortingEnabled)
        self.ADD_CHNNEL_BTN.setText(_translate("MainWindow", "Add Channel"))
        self.UPDATE_ID_BTN.setText(_translate("MainWindow", "Update"))
        self.label_8.setText(_translate("MainWindow", "New Channel Name:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Chat"))
        self.label.setText(_translate("MainWindow", "Address:"))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.label_3.setText(_translate("MainWindow", "Proxy:"))
        self.label_4.setText(_translate("MainWindow", "Port:"))
        self.pushButton_2.setText(_translate("MainWindow", "Test and Connect"))
        self.label_5.setText(_translate("MainWindow", "No Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Setting"))
        self.menuMenu.setTitle(_translate("MainWindow", "Contact us"))
        self.actionGitHub.setText(_translate("MainWindow", "GitHub"))
        self.actionTrello.setText(_translate("MainWindow", "Trello"))

